# Site settings
title: Jamie Zhang's design blog
email: jz651@uowmail.edu.au
description: > #Jamie Zhang's design blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liuyanwei.jumppo.com" # the base hostname & protocol for your site
twitter_username: littlejzhang@qq.com
github_username:  jamiejiezhang

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html
paginate: 10
author:
  name: Jamie Zhang 张婕
  email: jz651@uowmail.edu.au
  link: http://www.jamiejiezhang.com/
  weibo: http://weibo.com/
  github: http://github.com/jamiejiezhang
title: Jamie Zhang's design blog

# avatar & Favicon
avatar: https://avatars.githubusercontent.com/u/14763343?v=3&amp;s=460
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:
  tags: Tags
  about: About
active: Design
subscribe_rss: /pages/atom.xml
markdown: redcarpet

# google analytics setting
#ga:
#  id:
#  url:
#

# disqus settings
disqus:
  shortname: yang_xia